name: Fibonacci Bot

on:
  pull_request:
    types: [opened, edited]

jobs:
  fibonacci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Fibonacci Action
        uses: ./ # Use the path to your action
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          INPUT_PR_NUMBER: ${{ github.event.pull_request.number }}
